export const ROUTES = {
  splash: '/' as const,
  loading: '/loading' as const,
  home: '/(tabs)/' as const,
  worldMap: '/(tabs)/worlds' as const,
  museum: '/(tabs)/museum' as const,
  collection: '/(tabs)/collection' as const,
  profile: '/(tabs)/profile' as const,
  world: (worldId: string) => `/world/${worldId}` as const,
  play: (worldId: string, levelId: string) => `/play/${worldId}/${levelId}` as const,
  missions: '/missions' as const,
  dailyReward: '/daily-reward' as const,
  settings: '/settings' as const,
  parentMode: '/settings/parent-mode' as const,
  shop: '/shop' as const,
  leaderboard: '/leaderboard' as const,
  statistics: '/statistics' as const,
} as const;
